name: Python CI

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Syntax Check
        run: |
          python -m py_compile src/extract/company_details.py
          python -m py_compile src/load/init_db.py
          python -m py_compile src/load/load_company_master.py
          python -m py_compile src/load/company_master.py
          python -m py_compile src/load/tickers.py
          python -m py_compile src/pipeline/run.py
          python -m py_compile src/config/db.py
